version: '3'
services:
    webserver-php-turorial:
        image: php:latest
        build: ./webserver
        environment:
            - DB_SERVER=${DB_SERVER}
            - DB_USER=${DB_ROOT_USER}
            - DB_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - ./websites:/var/www/student
        depends_on:
            - mysql-php-tutorial
        expose:
            - 80
        ports:
            - 80:80
    mysql-php-tutorial:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
        depends_on:
            - webserver-php-turorial
            - mysql-php-tutorial
volumes:
    mysqldata: {}
